spring:
  application:
    name: task-and-time-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/task_and_time_tracker
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: INFO

jwt:
  secret: ${JWT_SECRET}
  ttl-millis: ${JWT_TTL:604800000}