
services:
  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_and_time_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: